# -*- coding: utf-8 -*-
"""Simple_Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i056o8de6g9y0Ip4bJdYIlAH_cWUCu3P
"""

!pip install nltk

import nltk
from nltk.chat.util import Chat, reflections
import os

nltk.download('punkt')

# Creating a simple chatbot using NLTK
pairs = [
    ["hello|hi|hey", ["Hi there!", "Hello!", "Hey!"]],
    ["how are you|how's it going", ["I'm good, thank you!", "I'm doing well."]],
    ["what is your name", ["I'm a simple chatbot."]],
    ["exit|quit", ["Goodbye!", "See you later!"]],
    ["open (.+)", ["Opening {}...", lambda app: os.system(f"start {app}")]],
    ["search (.+)", ["Searching for {}...", lambda query: os.system(f"start https://www.google.com/search?q={query}")]],
    [".*", ["I'm sorry, I don't understand that."]],
]

chatbot = Chat(pairs, reflections)

print("Hello! I'm here to assist you. Type 'exit' or 'quit' to end the conversation.")
while True:
    user_input = input("You: ")
    if user_input.lower() in ['exit', 'quit']:
        print("Chatbot: Goodbye!")
        break

    response = chatbot.respond(user_input)
    print(f"Chatbot: {response}")